# Generated by Django 5.2.12 on 2026-09-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Jméno')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Předmět')),
                ('message', models.TextField(verbose_name='Zpráva')),
                ('status', models.CharField(choices=[('new', 'Nevyřešeno'), ('resolved', 'Vyřešeno'), ('archived', 'Archiv')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
