"""
Django settings for lajseklegal project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-6z80#d2rbagq!_7b7c^&_gh=n3q)@6)_e$ois8+fa7(e11q9xj',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Na produkci NASTAVTE env proměnnou DJANGO_DEBUG=False (např. v systemd unit
# souboru přidejte řádek "Environment=DJANGO_DEBUG=False"), jinak Django
# zobrazuje citlivé ladicí stránky místo custom 404 a prozrazuje strukturu kódu.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Absolutní URL webu — používá se pro Open Graph tagy, sitemap.xml a JSON-LD.
SITE_URL = os.environ.get('SITE_URL', 'https://lajseklegal.cz')

# Google Analytics 4 — nastavte GA_MEASUREMENT_ID (např. "G-XXXXXXXXXX") až
# založíte property v Google Analytics. Dokud je prázdné, snippet se nevykreslí.
GA_MEASUREMENT_ID = os.environ.get('GA_MEASUREMENT_ID', '')

ALLOWED_HOSTS = [
    'lajseklegal.cz',
    'www.lajseklegal.cz',
    'localhost',
    '127.0.0.1',
    '178.104.193.54',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'core',
    'services',
    'blog',
    'dashboard',
    'engagement',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.SessionLanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lajseklegal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.language',
                'core.context_processors.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'lajseklegal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'cs'

TIME_ZONE = 'Europe/Prague'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Přidá otisk obsahu do jména souboru (style.a1b2c3.css) při každém collectstatic,
# takže CDN/prohlížeč cache nikdy neuvidí zastaralý soubor pod stejnou URL.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage',
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# E-mail — dokud nemáme SMTP heslo od Vladimíra, e-maily se jen vypisují do konzole.
# Až heslo bude k dispozici, přepnout EMAIL_BACKEND na 'django.core.mail.backends.smtp.EmailBackend'
# a doplnit EMAIL_HOST / EMAIL_HOST_USER / EMAIL_HOST_PASSWORD / EMAIL_PORT / EMAIL_USE_TLS.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@lajseklegal.cz'
ADMIN_NOTIFICATION_EMAIL = 'vlajsek@lajseklegal.cz'

# Rezervační systém — výchozí dostupné dny/hodiny nastaví migrace
# engagement.0003; dál se upravuje přes dashboard (BookingSettings model).
