# Generated by Django 5.2.12 on 2026-09-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('client_name', models.CharField(max_length=120, verbose_name='Jméno')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('status', models.CharField(choices=[('pending', 'Čeká na potvrzení'), ('confirmed', 'Potvrzeno'), ('cancelled', 'Zrušeno')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Otázka')),
                ('answer', models.TextField(verbose_name='Odpověď')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Pořadí')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivní')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='Jméno')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Hodnocení')),
                ('text', models.TextField(verbose_name='Text recenze')),
                ('approved', models.BooleanField(default=False, verbose_name='Schváleno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
