# Generated by Django 5.2.12 on 2026-09-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_seed_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.JSONField(default=list, help_text='0=pondělí … 6=neděle', verbose_name='Dny v týdnu')),
                ('hours', models.JSONField(default=list, help_text='Celé hodiny, kdy začíná schůzka, např. [9, 10, 11]', verbose_name='Hodiny')),
                ('days_ahead', models.PositiveIntegerField(default=21, verbose_name='Kolik dní dopředu nabízet')),
            ],
            options={
                'verbose_name': 'Nastavení rezervací',
                'verbose_name_plural': 'Nastavení rezervací',
            },
        ),
    ]
