# Generated by Django 5.2.12 on 2026-09-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_bookingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, help_text='Nepovinné, viz otázka výše.', verbose_name='Odpověď (anglicky)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, help_text='Nepovinné. Pokud vyplníte, anglická verze webu zobrazí tuto otázku místo automatického originálu.', max_length=255, verbose_name='Otázka (anglicky)'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(blank=True, help_text='Nepovinné. Pokud vyplníte, anglická verze webu zobrazí tento text místo automatického originálu.', verbose_name='Text recenze (anglicky)'),
        ),
    ]
