# Generated by Django 5.2.12 on 2026-09-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('published_at', models.DateField()),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
