from django.db import migrations

SLUG = 'otravne-reklamni-telefonaty-co-delat'

NEW_BODY = (
    'Neznámé číslo, pár vteřin hovoru a hned nabídka levnější elektřiny, '
    'nového tarifu nebo „výhodné investice“. Mnoho lidí má pocit, že proti '
    'podobným telefonátům nic nezmůže. Ve skutečnosti ale spotřebitel '
    'chráněný je — a firma si dnes nemůže volat komu chce. Tady je '
    'praktický návod, jak se proti otravnému cold callingu bránit.\n\n'
    'Reklamní telefonáty patří k nejčastějším formám obtěžování '
    'spotřebitelů. Typický scénář je jednoduchý: zavolá neznámé číslo, '
    'volající mluví rychle, tváří se přátelsky, ale ve skutečnosti se vás '
    'snaží dostat do obchodního jednání, o které jste vůbec nestáli.\n\n'
    'Dobrá zpráva je, že takové volání nemusíte brát jako běžnou součást '
    'života. Česká pravidla pro ochranu spotřebitele, pravidla pro '
    'elektronické komunikace i ochrana osobních údajů dávají spotřebitelům '
    'poměrně silné postavení.\n\n'
    'Může vám firma volat jen tak?\n\n'
    'Ve většině případů ne.\n\n'
    'Pro telefonický marketing dnes obecně platí, že podnikatel nemá '
    'volnou ruku k tomu, aby obvolával spotřebitele, kteří předem nedali '
    'najevo, že si takový kontakt přejí. Jinak řečeno: reklamní hovor by '
    'neměl být výchozí způsob, jak se firma k běžnému spotřebiteli '
    'dostane.\n\n'
    'To je důležitý posun oproti tomu, co si mnoho lidí myslí. Neplatí, že '
    'když firma „někde sehnala číslo“, může bez dalšího zavolat a nabídnout '
    'cokoliv.\n\n'
    'Co musí volající udělat hned na začátku hovoru\n\n'
    'Pokud už k hovoru dojde, volající by měl hned na začátku jasně říct:\n\n'
    'kdo je,\n'
    'za jakou firmu jedná,\n'
    'a že jde o obchodní nebo marketingový hovor.\n\n'
    'Spotřebitel nemá být v nejistotě, jestli jde o průzkum, zákaznickou '
    'péči nebo skrytou obchodní nabídku. Pravidla jsou nastavená tak, aby '
    'člověk už v prvních vteřinách věděl, s kým mluví a proč.\n\n'
    'Nestačí obyčejné „ano“ do telefonu\n\n'
    'Tohle je jedna z nejdůležitějších věcí, kterou by měl spotřebitel '
    'vědět.\n\n'
    'Samotné „ano“ během telefonátu obvykle nestačí k tomu, aby vznikla '
    'závazná spotřebitelská smlouva. Pokud firma nabízí něco po telefonu, '
    'musí nabídku následně potvrdit v textové podobě a spotřebitel ji musí '
    'potvrdit zvlášť.\n\n'
    'Prakticky řečeno: pokud po hovoru přijde e-mail, SMS nebo dokument k '
    'potvrzení, právě až tam často nastává rozhodující okamžik. Ne v '
    'průběhu samotného hovoru.\n\n'
    'Proto je vždy bezpečnější říct:\n\n'
    '„Pošlete mi to písemně, nic teď po telefonu nepotvrzuji.“\n\n'
    'Kdy už je reklamní telefonát problém\n\n'
    'Problém není jen samotné nevyžádané volání. Potíže bývají i v tom, '
    'jak firma během hovoru jedná.\n\n'
    'Pozor by si měl spotřebitel dát hlavně tehdy, když volající:\n\n'
    'neřekne jasně, že jde o obchodní nabídku,\n'
    'zatají cenu nebo délku závazku,\n'
    'mluví rychle a nepřehledně,\n'
    'vzbuzuje dojem, že jde jen o „ověření údajů“,\n'
    'tlačí na okamžité rozhodnutí,\n'
    'nebo tvrdí, že už jste s něčím souhlasili, i když ne.\n\n'
    'Takové jednání může být v rozporu s pravidly ochrany spotřebitele. '
    'Soudy navíc opakovaně zdůrazňují, že důležité informace nesmějí být '
    '„schované“ v proudu řeči tak, aby je běžný člověk při nevyžádaném '
    'hovoru vůbec nestihl rozumně vnímat.\n\n'
    'Jak se bránit během hovoru\n\n'
    'Nemusíte se pouštět do dlouhé debaty. Často je nejlepší krátká, '
    'klidná a jednoznačná reakce.\n\n'
    'Můžete říct například:\n\n'
    '„Nepřeji si další marketingové hovory.“\n'
    '„Žádám, abyste moje číslo vyřadili z databáze.“\n'
    '„Sdělte mi, odkud máte moje telefonní číslo.“\n'
    '„Pokud tvrdíte, že máte můj souhlas, tímto ho odvolávám.“\n'
    '„Nesouhlasím se zpracováním mých osobních údajů pro marketing.“\n\n'
    'Tohle nejsou jen „silná slova“. Spotřebitel má opravdu právo se '
    'bránit i přes pravidla ochrany osobních údajů. Pokud firma používá '
    'vaše číslo pro přímý marketing, můžete chtít vědět, odkud ho '
    'získala, můžete vznést námitku proti dalšímu používání a v řadě '
    'případů žádat i výmaz.\n\n'
    'Co dělat, aby už příště nevolali\n\n'
    'Pokud chcete, aby firma vaše číslo přestala používat, je dobré být '
    'co nejkonkrétnější. Nestačí jen říct „nemám zájem“. Lepší je '
    'výslovně požadovat, aby vás už nekontaktovali.\n\n'
    'Nejpraktičtější je spojit několik požadavků dohromady:\n\n'
    'že chcete vědět, odkud firma číslo získala,\n'
    'že si nepřejete další marketingové telefonáty,\n'
    'že žádáte vyřazení čísla z databáze,\n'
    'a že případný souhlas s marketingem odvoláváte.\n\n'
    'Pokud máte k dispozici e-mail firmy, je vhodné to samé poslat ještě '
    'písemně. Písemná stopa se hodí, pokud by se situace opakovala.\n\n'
    'Když hovory pokračují\n\n'
    'Pokud firma volá znovu a znovu, už nejde jen o nepříjemnost. V takové '
    'chvíli je dobré začít si vše zapisovat:\n\n'
    'datum a čas hovoru,\n'
    'telefonní číslo,\n'
    'název firmy,\n'
    'stručný obsah hovoru.\n\n'
    'To je důležité pro případ, že se rozhodnete obrátit na příslušný úřad '
    'nebo situaci řešit právně.\n\n'
    'Podle okolností může připadat v úvahu:\n\n'
    'podnět kvůli nevyžádanému marketingovému volání,\n'
    'podnět kvůli nekalému nebo nátlakovému jednání,\n'
    'nebo řešení přes ochranu osobních údajů.\n\n'
    'Co dělat, když jste už něco odsouhlasili\n\n'
    'Pokud máte po hovoru pocit, že jste možná něco potvrdili, '
    'nepropadejte panice. Důležité je rychle zkontrolovat, co vám firma '
    'poslala, a neignorovat následný e-mail, SMS nebo smluvní '
    'dokumentaci.\n\n'
    'U spotřebitelských smluv uzavíraných na dálku často existuje '
    'možnost od smlouvy odstoupit. Každý případ ale závisí na okolnostech '
    '— zejména na tom, co bylo skutečně potvrzeno, jaké informace firma '
    'poskytla a zda šlo o běžnou spotřebitelskou smlouvu.\n\n'
    'Právě tady už se často vyplatí rychlá právní konzultace.\n\n'
    'Reklamní telefonáty: co dělat krok za krokem\n\n'
    'Nic po telefonu nepotvrzujte.\n'
    'Zjistěte, kdo volá a za jakou firmu jedná.\n'
    'Zeptejte se, odkud mají vaše číslo.\n'
    'Řekněte výslovně, že si nepřejete další marketingové hovory.\n'
    'Požadujte vyřazení čísla z databáze.\n'
    'Odvolejte souhlas, pokud se na něj firma odvolává.\n'
    'Vznesete námitku proti používání osobních údajů pro marketing.\n'
    'Zapište si datum, čas, číslo a název firmy.\n'
    'Pokud volání pokračují, pošlete požadavek i písemně.\n'
    'Když je situace vážnější, řešte ji s odborníkem.\n\n'
    'Vladimír Lajsek'
)


def update_body(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    BlogPost.objects.filter(slug=SLUG).update(body=NEW_BODY)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_update_opotrebeni_body'),
    ]

    operations = [
        migrations.RunPython(update_body, noop),
    ]
